#!/bin/bash
#to install iraf...

echo "Running installation commands."

cd ~/Downloads

echo "Getting libraries:"

echo "tcsh"
sudo apt-get install tcsh

echo "libxssl"
sudo apt-get install libxssl

wget http://www.astronomy.ohio-state.edu/~khan/iraf/ldso_1.9.11-15_i386.deb
sudo dpkg -i ldso_1.9.11-15_i386.deb

wget http://www.astronomy.ohio-state.edu/~khan/iraf/libc5_5.4.46-15_i386.deb
sudo dpkg -i libc5_5.4.46-15_i386.deb

wget http://www.astronomy.ohio-state.edu/~khan/iraf/termcap-compat_1.2.3_i386.deb
sudo dpkg -i termcap-compat_1.2.3_i386.deb
